name: basics-actions
env:
  APPLICATION_NAME: "MyFlask"
  DEPLOY_PACKAGE_NAME: "flask-deploy-ver-${{ github.sha }}"
on:
  push:
      branches:
       - main

jobs:
  my_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello message in testing
        run: echo "Hello world from testing"
        
      - name: Execute few commands
        run: |
          echo "Hello again"
          echo "my friend"
          echo "App name is ${{ env.APPLICATION_NAME }}"
          
      - name: What inside?
        run: ls -la      
      - name: Git clone repo
        uses: actions/checkout@v1
      - name: What inside now?
        run: ls -la    

  my_deploing:
    runs-on: ubuntu-latest
    needs: [my_testing]
    env:
      VAR1: "This is job level Variable1"
      VAR2: "This is job level Variable2"
    steps:
      - name: Print hello message in deploing
        run: echo "Hello world from deploing"
      - name: Print deployment package
        run: echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"      
      - name: Lets test some packages if they are here 1
        run: aws --version
      - name: Lets test some packages if they are here 2
        run: zip --version      
      - name: Print some env
        run: |
          echo "Var1 = ${{ env.VAR1 }}"
          echo "Var2 = ${{ env.VAR2 }}"
          echo "Var3 = $LOCAL_VAR"
        env:
          LOCAL_VAR: "This is super local environment variable"
        
        
